apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calunga--runtime-int
namePrefix: calunga-
resources:
  - ../../base
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
images:
  - name: quay.io/calungaproject/releases-watcher
    newName: quay.io/rhopp/calunga-release-watcher
    digest: sha256:a25aa3c32845d03ea483e2f12aaf481a10b451e7775319bf676957f4ccfe7905
