apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calunga-release-watcher
  namespace: calunga--runtime-int
spec:
  project: default
  source:
    repoURL: https://github.com/rhopp/releases-watcher.git
    targetRevision: codex/dno-watcher-gitops
    path: deploy/overlays/calunga
  destination:
    server: https://kubernetes.default.svc
    namespace: calunga--runtime-int
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
